apiVersion: v1
kind: ConfigMap
metadata:
  name: "interlink-config"
  namespace: interlink 
data:
  InterLinkConfig.yaml: |
    InterlinkAddress: "http://0.0.0.0"
    InterlinkPort: "3000"
    #SidecarURL: "http://plugin.interlink.svc.cluster.local"
    SidecarURL: "http://plugin"
    SidecarPort: "4000"
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ExportPodData: true
    DataRootFolder: "~/.interlink"
