target_nodes:
  - virtual-kubelet

required_namespaces:
  - default
  - kube-system
  - interlink

timeout_multiplier: 20.
values:
  namespace: interlink

  annotations: {}
  #   slurm-job.vk.io/flags: "--job-name=test-pod-cfg -t 2800  --ntasks=8 --nodes=1 --mem-per-cpu=2000"

  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists
      effect: NoSchedule

